### ISSUE TITLE
Make the sidebar remember the last zoom value

### ISSUE THREAD

**Issue by Leonardclc** [Soushi-Atsumi/Search-in-Sidebar#2]
I need this sidebar to show me a calculation result on on google, but the result wont show up unless i zoom out the page or scroll it, which is not pratical and takes a lot of time. Making it remember the zoom value will save me a lot of time, because currently everytime i make a new search the zoom value resets. Thanks for your hard work!

**Comment by Soushi-Atsumi** [comment]
Hi, leoweabo.

This extension cannot access any pages because it doesn't have the permission. Even if it has it, I don't know I can change the level of zoom or not.
By the way, I also think that having the zoom capability is better.
If Mozilla has implemented an api for zooming in the future, the feature will be added to this extension.

**Comment by Soushi-Atsumi** [comment]
It seems that Mozilla will never implement the feature.
