### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by benyaminl** [Soushi-Atsumi/Search-in-Sidebar#3]
The Search in sidebar now still showing desktop UI, which is hard to navigate to
example 
![image](https://user-images.githubusercontent.com/2817332/161363452-0a70fc50-8790-4ede-a33e-0a7bc91da6be.png)
As we can to reach edge capability in Firefox, then we must able to make it sniff the user agent to serve the mobile view, like 
![image](https://user-images.githubusercontent.com/2817332/161363486-47ea44b2-d631-43cd-96f0-149cb74fe62e.png)

**Comment by benyaminl** [comment]
Related to https://github.com/mdn/webextensions-examples/blob/master/user-agent-rewriter/background.js

**Comment by Soushi-Atsumi** [comment]
Hi, benyaminl.

There are some problems to display the sidebar as a mobile view with rewriting User-Agent.
1. User-Agent which is smart phone does not always make a site displaying a mobile view.
2. Changing User-Agent effects non-sidebar tabs.
3. Changing User-Agent requires the additional permission.
4. Changing User-Agent in only a sidebar is impossible because API cannot get the tab id of the sidebar.

This is the same issue to #1.

**Comment by benyaminl** [comment]
On most search engine, it solve the issue, because they server different
css for different UA.

I only test it on:
1.duckduckgo
2.google
3.bing
4.yahoo
6.ask
7.qwant
8.searx

I don't know the rest, but it will make its simpler for the maintainer
rather than forcing inject css/js to each site that used to be loaded in
sidebar

for 2nd no tab ID, I have some suggestion regarding it. Well it require
more permission, but we can disable it like other addons do, using toggle,
and since your addons is open source, most people can review the code.

Well your addon is the only addon on the market that support such feature
that make Firefox on par with edge, as they become more more user centric
than ever (base on telemetry, a lot of user use sidebar to search on edge
using bing, their marketshare jump).



Regards,
Benyamin Limanto
sent from my Sony XPERIA XZ Premium
